### ISSUE TITLE
Group Resources spams the Player.log

### ISSUE THREAD

**Issue by pixelkritzel** [anpilley/OniModSet#6] opened 2023-01-10 10:24 UTC
Just looked at my Player.log file and found for every tick a lot of logs from Grouped Resources. Disabling the mod seems to improve my performance by ~20%. Maybe there are some low hanging fruits.

[Link to player.log](https://raw.githubusercontent.com/pixelkritzel/uploads/main/Player.log)

**Comment by anpilley** [comment] 2023-01-10 15:13
Hey, thanks for the report. I'm not sure that the log spam is actually the cause of your performance issues, since it doesn't actually happen once per frame, and the performance doesn't really change with that log message removed. Although I'll definitely clean that up, not sure how that one slipped through, there might be something else going on I'll dig into as well when I get a chance, it may have just been a red herring. 

That said, it'd be super if you didn't post callout threads on reddit when you're having an issue with a mod, without at least giving the developer a chance to read your bug report, instead of, you know, sleeping.

**Comment by pixelkritzel** [comment] 2023-01-10 16:31
> That said, it'd be super if you didn't post callout threads on reddit when you're having an issue with a mod, without at least giving the developer a chance to read your bug report, instead of, you know, sleeping.

Sorry. I didn't mean to call you personally. This why I didn't link your mod initially. But after somebody linked to a different mod I wanted to clarify things. And also I looked beforehand on the opened and closed issues here on Github. No closed ones and others open for months was the other point why I decided to share this possible performance improvement. A lot of bases get abandoned because of FPS death. But I get your position. Hopefully I didn't ruin your day.

For me disabling the mod made a huge difference. Sadly so because I like the mod a lot and I think the UX is much better than the vanilla version. Thank you!

**Comment by anpilley** [comment] 2023-01-10 17:26
Okay, well, I suspect that the log output is a bit of a red herring. Unity's logging system buffers output, so it's not stopping every line to commit it to the log file, the impact of that specifically shouldn't be humongous (although it's obviously not helpful and I've removed it.)

The main issue is that ONI has some really bad performance issues under the covers. World Inventory updates very frequently, far more often than it needs to, and that triggers a refresh of the pinned resources often, even when there isn't a change in the tracked inventory. But there's nothing that really indicates whether the update is due to an inventory change, a newly pinned or discovered resource, or switching asteroids in the DLC, the entry-path is more or less the same no matter what. 

There are some things around visibility that I'm doing during these updates that might have a higher than expected UI cost, and I'll see what I can do to reduce that impact.

One of the reasons why I might not be seeing the impact as greatly here, is that I've currently for Fast Track enabled, which caches world inventory updates to reduce their frequency by a large amount. Fast track has that effect on pretty much every area of the game that it adds caching for. If you're not using Fast Track, I suggest giving it a shot, it can help improve performance a lot, although it's obviously not a fix for this issue.

**Comment by pixelkritzel** [comment] 2023-01-10 18:11
About Fast Track: My dupes instant starve while eating with Fast Track . It's a weird bug that even happens with my new machine.  Couldn't figure this one out yet.

And big yes to the weird Unity/ONI performance issues. Especially while Fat Track manages to improve the performance so much just by patching methods.

**Comment by anpilley** [comment] 2023-01-10 18:35
I hope you filed a bug with Fast Track about that starving issue, that's an odd one, but FT has caused all sorts of weird issues due to base game race conditions popping up. You should try disabling dupe chore optimization in the Fast Track settings and see how you get on with it, those have definitely triggered some odd behavior for me (My dupes were slow-walking to recreation rooms for some weird reason, but it's been mostly addressed in FT 0.10.1.)

On my end, some other people in the modding discord haven't been able to replicate any performance issues with Grouped Resources yet. There's still definitely some stuff I'm going to update and we'll see if that helps when I can get an update out.

Can you do me a favor, and zip up your save and attach it, along with the output of the dxdiag tool in windows (launch it and hit "Save all information") so I can get a better picture of your PC's specs? Right now, the only thing I know about it is that you have a 3080, which is on par with my 3070ti. If I can use your save as a benchmark that'd be helpful.

**Comment by pixelkritzel** [comment] 2023-01-10 20:27
I already tried this. But disabling the dupe optimizations led to another performance regression. So I thought this base was done. This is the last save game where Grouped resources where active from yesterday. Hopefully you can find something.

https://github.com/pixelkritzel/uploads/raw/main/Restart%20This%20Ocean%20-%20Diag.zip

**Comment by pixelkritzel** [comment] 2023-01-10 20:30
The other way around. I deactivated everything except the dupe optimizations in hope of replicating the bug.

**Comment by anpilley** [comment] 2023-01-10 22:48
Well, first glance, you've got a more powerful cpu, the same amount of ram, and a better GPU (not that it matters much for ONI) than I do. I'm on an i7-12700K, for comparison.

I can't replicate any significant performance difference between having GR on and off with your save. I am missing several of your mods, though. I checked with critter inventory, since that's the only other mod affecting the same area, but nothing changed there. None of your other mods jump out as being specifically likely to cause any direct interactions with my mod, but it could be altering the base FPS you're seeing, so you're at a lower baseline, perhaps.

But yeah, I'm getting ~30fps at 3x speed on your main asteroid with my mod, and ~30fps at 3x speed without it. The caveat is that 30fps is where the game starts cutting back on critter AI and various other things to try and maintain game visual performance, so it's possible it's being hidden, but it's not dramatic either way.

Anyway, I'll see if i can make some changes over the next couple of days to cache some visibility updates I make, but there's likely not a whole lot more I can do beyond that, ONI really just calls updates in the pinned resource lists way more frequently than it should. 

I'll also install a few more of the mods you've got and try it again to see if I can shake loose anything else, if there's a bad interaction with my mod, I'd like to know about it.

That said, you should follow up with the FT dev about your issues with it. Getting that working for yourself will dramatically improve your experience in a late game base like that. You might be running into race conditions with some of your other mods, but it's worth looking into. With Fast Track on, your base went from 30fps for me, up to 55fps, basically.

**Comment by pixelkritzel** [comment] 2023-01-11 00:59
Thank you! Do you also experience a slowdown after like 90 - 1290 minutes of playtime? It feels like a memory leak. With ONI in general?

**Comment by anpilley** [comment] 2023-01-11 02:11
Hm, not that I've generally noticed, but I haven't played too much with some of the more recent patches. The Fast Track dev usually has a much better idea about that than I would.

**Comment by pixelkritzel** [comment] 2023-01-13 12:37
So I tested it more and I'm sorry. I couldn't replicate my performance improvement by deactivating your mod.

Also tried to clarify it on [Reddit](https://www.reddit.com/r/Oxygennotincluded/comments/10atibq/correction_grouped_resources_wasnt_the_fps_hog_i/)

**Closed as completed** 2023-01-16 22:55 UTC
Labels: bug
